[theme]
primaryColor="#4B8BBE"
backgroundColor="#f0f2f6"
secondaryBackgroundColor="#ffffff"
textColor="#262730"
font="sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[pages]
defaultPage = "Scoring Explained"
